CREATE TABLE IF NOT EXISTS posts(
    id int PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    user_id int NOT NULL,
    content VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)